name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-release:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
      - name: Build binary
        run: zig build -Doptimize=ReleaseFast
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            zig-out/bin/ctx
            ctx-prompt.bash
            LICENSE
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          with:
            files: |
              zig-out/bin/ctx
              ctx-prompt.bash
              LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
