name: test

on:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        zig: [0.14.1]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Zig ${{ matrix.zig }}
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig }}

      - name: Print compiler version
        run: zig version

      - name: Run unit tests
        run: zig build test
