name: test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
      - name: Add zig-out/bin to PATH
        run: echo "${{ github.workspace }}/zig-out/bin" >> $GITHUB_PATH
      - name: Run tests
        run: zig build test
